### ISSUE TITLE
67xx laser control issue

### ISSUE THREAD

**Issue by supernight3** [gregmoille/InstrumentControl#3]
### Position of the issue
[https://github.com/gregmoille/InstrumentControl/blob/master/pyLaser/HowToNewFocus.md](url)
### Description of the issue
How can I find drivers named 'sfkdsdf' and 'sldkflskd'? Are they a must for the successful running of newfocus.py?

**Comment by gregmoille** [comment]
Well... it was obviously a draft and there is no driver named after the gibberish I wrote, sorry about that. 
You can have a look at the newfocus function on line [109](https://github.com/gregmoille/InstrumentControl/blob/30e7bbfd2f73f5821b3ddd766d9abac5a294c22d/pyLaser/newfocus.py#L109) : `Assembly.LoadFile(dllpath + 'UsbDllWrap.dll')`. You would have to place the dll file in the`C:\ProgramData\Anaconda3\DLLs\` folder or otherwise tweak line [108](https://github.com/gregmoille/InstrumentControl/blob/30e7bbfd2f73f5821b3ddd766d9abac5a294c22d/pyLaser/newfocus.py#L108C23-L108C59) of the file. Note that I provide a version of the dll which may or may not be the latest version and/or compatible with your TLB controller
